// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBootTimings():Promise<main.BootTimings>;

export function Greet(arg1:string):Promise<string>;

export function SaveAndOpenPDF(arg1:string,arg2:string):Promise<string>;

export function SetBootTimings(arg1:main.BootTimings):Promise<void>;
