// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootTimings() {
  return window['go']['main']['App']['GetBootTimings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetBootTimings(arg1) {
  return window['go']['main']['App']['SetBootTimings'](arg1);
}
