// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1) {
  return window['go']['services']['AuthService']['ChangePassword'](arg1);
}

export function GetAllUsers() {
  return window['go']['services']['AuthService']['GetAllUsers']();
}

export function GetUserByID(arg1) {
  return window['go']['services']['AuthService']['GetUserByID'](arg1);
}

export function HasUsers() {
  return window['go']['services']['AuthService']['HasUsers']();
}

export function Login(arg1) {
  return window['go']['services']['AuthService']['Login'](arg1);
}

export function Register(arg1) {
  return window['go']['services']['AuthService']['Register'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['services']['AuthService']['UpdateUser'](arg1);
}
