// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['services']['UpdateService']['CancelDownload']();
}

export function CheckForUpdate() {
  return window['go']['services']['UpdateService']['CheckForUpdate']();
}

export function GetUpdateState() {
  return window['go']['services']['UpdateService']['GetUpdateState']();
}

export function InstallUpdate() {
  return window['go']['services']['UpdateService']['InstallUpdate']();
}

export function SkipVersion() {
  return window['go']['services']['UpdateService']['SkipVersion']();
}

export function StartDownload() {
  return window['go']['services']['UpdateService']['StartDownload']();
}
